title: Abhishek Singh
logo: /assets/IMG_3595.jpg
#description: Aspiring Data Analyst
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme # add this line to the plugins list if you already have one
